export const UPDATE_PLAYLIST_DATA = 'UPDATE_PLAYLIST_DATA';
export const CREATE_PLAYLIST_START = 'CREATE_PLAYLIST_START';
export const CREATE_PLAYLIST_FINISH = 'CREATE_PLAYLIST_FINISH';
export const CLEAR_CREATED_PLAYLIST = 'CLEAR_CREATED_PLAYLIST';
