export const CLEAR_SEARCH_RESULTS = 'CLEAR_SEARCH_RESULTS';
export const LOAD_SONGS_START = 'LOAD_SONGS_START';
export const LOAD_SONGS_FINISH = 'LOAD_SONGS_FINISH';
export const SEARCH_SONGS_START = 'SEARCH_SONGS_START';
export const SEARCH_SONGS_FINISH = 'SEARCH_SONGS_FINISH';