export const ADD_SONG_START = 'ADD_SONG_START';
export const ADD_SONG_FINISH = 'ADD_SONG_FINISH';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_FINISH = 'SEARCH_FINISH';
export const SELECT_SONG_START = 'SELECT_SONG_START';
export const SELECT_SONG_FINISH = 'SELECT_SONG_FINISH';
export const UPDATE_SONG_DATA = 'UPDATE_SONG_DATA';
