export const LOAD_PLAYLISTS_START = 'LOAD_PLAYLISTS_START';
export const LOAD_PLAYLISTS_FINISH = 'LOAD_PLAYLISTS_FINISH';
export const SELECT_PLAYLIST_START = 'SELECT_PLAYLIST_START';
export const SELECT_PLAYLIST_FINISH = 'SELECT_PLAYLIST_FINISH';
export const SLOW_IMPORT_START = 'SLOW_IMPORT_START';
export const SLOW_IMPORT_FINISH = 'SLOW_IMPORT_FINISH';
export const QUICK_IMPORT_START = 'QUICK_IMPORT_START';
export const QUICK_IMPORT_FINISH = 'QUICK_IMPORT_FINISH';
