export const ADD_SONG_START = 'ADD_SONG_START';
export const ADD_SONG_FINISH = 'ADD_SONG_FINISH';
export const SPOTIFY_ERROR = 'SPOTIFY_ERROR';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_FINISH = 'LOGIN_FINISH';
export const LOGOUT = 'LOGOUT';
export const SELECT_SONG_FINISH = 'SELECT_SONG_FINISH';
export const UPDATE_SONG_DATA = 'UPDATE_SONG_DATA';
